todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/<list_id>', views.delete, name='delete'),
    path('cross_off/<list_id>', views.cross_off, name='cross_off'),
    path('uncross/<list_id>', views.uncross, name='uncross'),
    path('edit/<list_id>', views.edit, name='edit'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todo.urls")),
]

todo/models.py
from django.db import models


class List(models.Model):
    item = models.CharField(max_length=300)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.item + '|' + str(self.completed)

todo/forms.py
from django import forms
from .models import List


class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['item', 'completed']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import List
from .forms import ListForm
from django.contrib import messages


def index(request):
    if request.method == 'POST':
        form = ListForm(request.POST or None)

        if form.is_valid():
            form.save()
            all_items = List.objects.all
            messages.success(request, 'Item has been added to list.')
            return render(request, 'todo/index.html', {'all_items': all_items})

    else:
        all_items = List.objects.all
        return render(request, 'todo/index.html', {'all_items': all_items})


def delete(request, list_id):
    item = get_object_or_404(List, pk=list_id)
    item.delete()
    messages.success(request, 'Item has been deleted.')
    return redirect('todo:index')


def cross_off(request, list_id):
    item = get_object_or_404(List, pk=list_id)
    item.completed = True
    item.save()
    return redirect('todo:index')


def uncross(request, list_id):
    item = get_object_or_404(List, pk=list_id)
    item.completed = False
    item.save()
    return redirect('todo:index')


def edit(request, list_id):
    if request.method == "POST":
        item = get_object_or_404(List, pk=list_id)

        form = ListForm(request.POST or None, instance=item)

        if form.is_valid():
            form.save()
            messages.success(request, 'Item has been edited.')
            return redirect('todo:index')

    else:
        item = get_object_or_404(List, pk=list_id)
        return render(request, 'todo/edit.html', {'item': item})

todo/templates/todo/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_css.css' %}">

    <title>Hello, world!</title>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'todo:index' %}">Todo List</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
          <input class="form-control mr-sm-2" type="search" placeholder="Add Item" aria-label="Search" name="item">
          <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add to List</button>
        </form>
      </div>
    </nav>
      <br/>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/edit.html
{% extends 'todo/base.html' %}

{% block content %}
    {% if item %}
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="{{ item.item }}"
                   value="{{ item.item }}"aria-label="Search" name="item">

            <input type="hidden" value="{{ item.completed }}" name="completed">

            <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Edit Item</button>
        </form>
    {% endif %}
{% endblock %}

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissable" role="alert">
            {{ message }}
            <button class="close" data-dismiss="alert">
                <small><sup>x</sup></small>
            </button>

        </div>
    {% endfor %}
    {% endif %}

    {% if all_items %}
        <table class="table table-bordered">
        {% for things in all_items %}
            {% if things.completed %}
                <tr class="table-secondary">
                    <td class="striker"><a href="{% url 'todo:edit' things.id %}">{{ things.item }}</a></td>
                    <td><center><a href="{% url 'todo:uncross' things.id %}">Uncross</a></center></td>
                    <td><center><a href="{% url 'todo:delete' things.id %}">Delete</a></center></td>
                </tr>
            {% else %}
                <tr>
                    <td><a href="{% url 'todo:edit' things.id %}">{{ things.item }}</a></td>
                    <td><center><a href="{% url 'todo:cross_off' things.id %}">Cross-off</a></center></td>
                    <td><center><a href="{% url 'todo:delete' things.id %}">Delete</a></center></td>
                </tr>
            {% endif %}
        {% endfor %}
        </table>
    {% endif %}

{% endblock %}